server:
  port: 9001
spring:
  application:
    name: ids-admin

  datasource:
        name: test
        url: jdbc:mysql://47.107.44.46:3306/vm?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: develop2019
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20   
management:
  security:
    enable: false
  endpoints:
     web:
       exposure:
         include: refresh,health
     endpoint:
       health:
         show-details: always
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      defaultZone: http://localhost:8761/eureka

node:
   cloudServer:
      #host: "192.168.3.12"
      host: "test refresh"
      port: "80"
   coreEngine:
      host: "192.168.3.12"
      ports:
        streamControl: 10600
        data: 10688
        deviceManagement: 10689
        deviceControl: 10604
        arbiterManagement: 10771
        config: 10687