server:
  port: 9001
spring:
  application:
    name: ids-admin
  data:
    mongodb:
      uri: mongodb://platform:platform@47.107.44.46:20001/platform
management:
  endpoints:
     web:
       exposure:
         include: "*"
     endpoint:
       health:
         show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

node:
   cloudServer:
      host: "192.168.3.12"
      port: "80"
   coreEngine:
      host: "192.168.3.12"
      ports:
        streamControl: 10600
        data: 10688
        deviceManagement: 10689
        deviceControl: 10604
        arbiterManagement: 10771
        config: 10687