server:
  port: 8761 
spring:
    application:
        name: ids-center   
eureka:
  client:
    server:
        //waitTimeInMsWhenSyncEmpty: 0
    //register-with-eureka: false
    //fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      