server:
    port: 8762
spring:
    application:
        name: ids-center
eureka:
    client:
      registerWithEureka: false  
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:8761/eureka