spring:
    application:
        name: ids-center   
server:
  port: 8761 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/

      