
spring:
    application:
        name: ids-center   

        
server:
  port: 8761
spring:
  profiles: node1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

      
      
server:
  port: 8762
spring:
  profiles: node2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/

      
      
server:
  port: 8763
spring:
  profiles: node3
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

